name: Install AUR packages with yay

on:
  schedule:
    - cron: "0 7 * * 3"
  workflow_dispatch:

jobs:
  aur-install:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Create non-root user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          mkdir -p /home/builder/aurbuild
          chown -R builder:builder /home/builder

      - name: Install base-devel and git
        run: pacman -Sy --noconfirm base-devel git sudo

      - name: Clone yay-bin from AUR
        run: sudo -u builder git clone https://aur.archlinux.org/yay-bin.git /home/builder/yay

      - name: Build and install yay
        run: |
          cd /home/builder/yay
          sudo -u builder makepkg -si --noconfirm

      - name: Configure yay to use custom build directory
        run: |
          sudo -u builder mkdir -p /home/builder/aurbuild
          sudo -u builder yay --noconfirm --save --builddir /home/builder/aurbuild

      - name: Install AUR packages with yay
        run: |
          sudo -u builder yay --noconfirm --builddir /home/builder/aurbuild -S \
            antimicrox-git lutris-git balena-etcher mkinitcpio-openswap \
            betterdiscord-installer-bin moonlight-qt-bin bottles opengamepadui-bin \
            patool coolercontrol-bin peazip-qt-bin \
            coolercontrold-bin polychromatic-git protonup-qt-bin \
            python-fvs python-pathvalidate python-steamgriddb \
            sunshine \
            sunshine-bin downgrade electron17-bin trizen gzdoom vkbasalt-cli \
            icoextract lgogdownloader libcprime yay-bin \
            libcsys zmusic linux-firmware-valve

      - name: Filter and copy non-debug packages
        run: |
          mkdir -p /home/builder/artifacts
          find /home/builder/aurbuild -maxdepth 1 -type f -name '*.pkg.tar.zst' ! -name '*-debug-*.pkg.tar.zst' \
            -exec cp {} /home/builder/artifacts/ \;

      - name: Rename packages (strip extensions)
        run: |
          cd /home/builder/artifacts
          for f in *.pkg.tar.zst; do
            base=$(echo "$f" | sed 's/-[^-]*-[^-]*\.pkg\.tar\.zst$//')
            mv "$f" "$base.pkg.tar.zst"
          done

      - name: Upload AUR packages
        uses: actions/upload-artifact@v4
        with:
          name: aur-packages
          path: /home/builder/artifacts/*.pkg.tar.zst
