name: Install AUR packages and update repo

on:
  schedule:
    - cron: "0 7 * * 3"  # Every Wednesday at 7:00 AM
  workflow_dispatch:

jobs:
  aur-install:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Create non-root user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          mkdir -p /home/builder/aurbuild
          chown -R builder:builder /home/builder

      - name: Install base-devel and git
        run: pacman -Sy --noconfirm base-devel git jq

      - name: Clone yay-bin from AUR
        run: su - builder -c 'curl -o PKGBUILD https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=yay-bin'

      - name: Build and install yay
        run: |
          su - builder -c 'cd /home/builder/ && makepkg -si --noconfirm'

      - name: Check if any AUR packages are flagged out-of-date
        run: |
          PACKAGES=(
            prismlauncher lutris-git opengamepadui-bin bottles gzdoom-bin yay-bin
            antimicrox-git balena-etcher coolercontrol-bin betterdiscord-installer-bin
            moonlight-qt-bin peazip-qt-bin polychromatic-git protonup-qt-bin sunshine-bin linux-firmware-valve
          )

          for pkg in "${PACKAGES[@]}"; do
            echo "Checking $pkg..."
            OUT_OF_DATE=$(curl -s "https://aur.archlinux.org/rpc/?v=5&type=info&arg=calamares" \ | jq '.results[0].OutOfDate')
            if [ "$OUT_OF_DATE" != "null" ]; then
              echo "Package '$pkg' is flagged out-of-date (timestamp: $OUT_OF_DATE)"
              exit 110
            fi
          done

      - name: Install AUR packages with yay
        run: |
          su - builder -c 'yay --noconfirm --save --builddir /home/builder/aurbuild -S \
          prismlauncher lutris-git opengamepadui-bin bottles gzdoom-bin yay-bin \
          antimicrox-git balena-etcher coolercontrol-bin betterdiscord-installer-bin \
          moonlight-qt-bin peazip-qt-bin polychromatic-git protonup-qt-bin sunshine-bin linux-firmware-valve'

      - name: Filter and copy non-debug packages
        run: |
          mkdir -p /home/builder/artifacts
          find /home/builder/aurbuild -type f -name '*.pkg.tar.zst' ! -name '*-debug-*.pkg.tar.zst' \
            -exec cp --dereference {} /home/builder/artifacts/ \;

      - name: Rename packages (strip extensions)
        run: |
          cd /home/builder/artifacts
          shopt -s nullglob
          for f in *.pkg.tar.zst; do
            base=$(echo "$f" | sed 's/-[^-]*-[^-]*\.pkg\.tar\.zst$//')
            mv "$f" "$base.pkg.tar.zst"
          done

      - name: Sanitize filenames (remove forbidden characters for GitHub Artifacts)
        run: |
          cd /home/builder/artifacts
          for f in *.pkg.tar.zst; do
            safe=$(echo "$f" | sed 's/[:<>\"|?*]/_/g')
            if [ "$f" != "$safe" ]; then
              echo "Renaming $f -> $safe"
              mv "$f" "$safe"
            fi
          done

      - name: Upload AUR packages
        uses: actions/upload-artifact@v4
        with:
          name: aur-packages
          path: /home/builder/artifacts/*.pkg.tar.zst

  update-repo:
    runs-on: ubuntu-latest
    needs: aur-install
    container:
      image: archlinux:latest

    steps:
      - name: Install pacman-contrib
        run: pacman -Sy --noconfirm pacman-contrib

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: staging

      - name: Clean x86_64 directory
        run: rm -f ./x86_64/*

      - name: Download AUR packages
        uses: actions/download-artifact@v4
        with:
          name: aur-packages
          path: ./x86_64

      - name: Import GPG private key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Trust GPG key
        run: |
          echo "53407B947EBAD024A4645885A139E9B289DC7527:6:" | gpg --import-ownertrust

      - name: Generate repo database
        run: |
          cd x86_64
          repo-add -s -k 53407B947EBAD024A4645885A139E9B289DC7527 edge-repo.db.tar.gz *.pkg.tar.zst

          unlink edge-repo.db
          unlink edge-repo.db.sig
          unlink edge-repo.files
          unlink edge-repo.files.sig
          mv edge-repo.db.tar.gz edge-repo.db
          mv edge-repo.db.tar.gz.sig edge-repo.db.sig
          mv edge-repo.files.tar.gz.sig edge-repo.files.sig
          mv edge-repo.files.tar.gz edge-repo.files

      - name: Sign packages
        run: |
          for pkg in ./x86_64/*.pkg.tar.zst; do
            gpg --armor --detach-sign --local-user 53407B947EBAD024A4645885A139E9B289DC7527 "$pkg"
          done

      - name: Rename .asc to .sig
        run: |
          cd x86_64
          for file in *.asc; do
            if [ -f "$file" ]; then
              mv "$file" "${file%.asc}.sig"
            fi
          done

      - name: Commit and push to staging
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add x86_64/*
          git commit -m "Update repo with signed packages"
          git push origin staging

