name: Mirror staging edge-repo to GitLab

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Always checkout GitHub staging branch
      uses: actions/checkout@v3
      with:
        ref: staging

    - name: Extract latest GitHub commit message
      id: commit_info
      run: |
        echo "commit_msg<<EOF" >> $GITHUB_OUTPUT
        git log -1 --pretty=format:'%B' >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Set up Git config with Mirror Bot identity
      run: |
        git config --global user.name "GitLab Mirror Bot"
        git config --global user.email "mirror-bot@edgedev1.gitlab"

    - name: Clone GitLab repo and push to staging branch
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        git clone https://oauth2:${GITLAB_TOKEN}@gitlab.com/edgedev1/edge-repo.git gitlab-mirror
        cd gitlab-mirror

        # Check out or create 'staging' branch
        if git ls-remote --exit-code --heads origin staging; then
          git checkout staging
        else
          git checkout -b staging
        fi

        cd ..
        rsync -av --exclude=gitlab-mirror ./ gitlab-mirror/
        cd gitlab-mirror


        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "${{ steps.commit_info.outputs.commit_msg }}"
          git push origin staging
        fi
